name: mushafmuscat
description: Mushaf Muscat App.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  material_design_icons_flutter: ^7.0.7296
  sliding_switch: ^1.1.0
  hexcolor: ^3.0.1
  flutter_svg: ^2.0.5
  url_launcher: ^6.1.11
  url_launcher_web: ^2.0.19
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  carousel_slider: ^4.2.1
  assets_audio_player: ^3.1.1
  http: ^1.1.2
  auto_size_text: ^3.0.0
  sizer: ^2.0.15
  flutter_screenutil: ^5.7.0
  share_plus: ^7.2.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  ios: true
  image_path: "assets/icons/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - lang/
    - assets/quran_images/
    - assets/quran_images/images/
    - lib/data/json_files/
    - lib/data/json_files/audio_page/
    - lib/data/json_files/quran_lines/
    - lib/data/json_files/tafsir_files/
  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 700

    - family: ScheherazadeNew
      fonts:
        - asset: assets/fonts/ScheherazadeNew-Bold.ttf
          weight: 700
    - family: Amiri
      fonts:
        - asset: assets/fonts/amiri-regular.ttf
